/**
 * AUTO-GENERATED by tools/sync-vehicle-catalog.mjs — do not edit by hand.
 * Source: shared/vehicle-catalog.json
 * SHA256: 778d1b6bfcf92295ff7303eec17f62d6921ae51790589756261330d4c9531273
 */
"use strict";

const catalog = require("./vehicle-catalog.data.json");

const CANONICAL_VEHICLE_IDS = Object.freeze([...catalog.canonicalVehicleIds]);
const LEGACY_VEHICLE_ALIASES = Object.freeze({ ...catalog.legacyAliases });
const VEHICLE_DISPLAY_LABEL_KEYS = Object.freeze({ ...catalog.displayLabelKeys });
const VALID_COMMISSION_RANGE = Object.freeze({ ...catalog.validCommissionRange });

const DEFAULT_VEHICLE_RATES = Object.freeze(
  Object.fromEntries(
    CANONICAL_VEHICLE_IDS.map((id) => [
      id,
      Object.freeze({
        baseFare: catalog.defaultRates[id].baseFare,
        perKmRate: catalog.defaultRates[id].perKmRate,
        commissionPercent: catalog.defaultRates[id].commissionPercent,
        distanceTiers: Object.freeze([]),
        paceTiers: Object.freeze([]),
      }),
    ])
  )
);

const DEFAULT_PRICING = Object.freeze({
  baseFare: DEFAULT_VEHICLE_RATES.go.baseFare,
  perKmRate: DEFAULT_VEHICLE_RATES.go.perKmRate,
  commissionPercent: DEFAULT_VEHICLE_RATES.go.commissionPercent,
  vehicles: DEFAULT_VEHICLE_RATES,
});

const CANONICAL_SET = new Set(CANONICAL_VEHICLE_IDS);
const LEGACY_MAP = new Map(
  Object.entries(LEGACY_VEHICLE_ALIASES).map(([legacy, canonical]) => [legacy.toLowerCase(), canonical])
);

const LABEL_TO_CANONICAL = new Map();
for (const [canonicalId, labels] of Object.entries(catalog.nameAliases || {})) {
  for (const label of labels) {
    LABEL_TO_CANONICAL.set(String(label).trim().toLowerCase(), canonicalId);
  }
  LABEL_TO_CANONICAL.set(canonicalId.toLowerCase(), canonicalId);
}

function normalizeVehicleTypeInput(raw) {
  return String(raw ?? "")
    .trim()
    .toLowerCase();
}

function isCanonicalVehicleTypeKey(canonicalId) {
  return CANONICAL_SET.has(canonicalId);
}

function resolveVehicleTypeKeyForRead(raw) {
  const input = normalizeVehicleTypeInput(raw);
  if (!input) {
    return { ok: false, code: "EMPTY_VEHICLE_TYPE", input: "" };
  }
  if (CANONICAL_SET.has(input)) {
    return { ok: true, canonicalId: input, source: "canonical", input };
  }
  const labelCanonical = LABEL_TO_CANONICAL.get(input);
  if (labelCanonical) {
    return {
      ok: true,
      canonicalId: labelCanonical,
      source: "label_alias",
      input,
      legacyAlias: input !== labelCanonical ? input : undefined,
    };
  }
  const legacyCanonical = LEGACY_MAP.get(input);
  if (legacyCanonical) {
    return {
      ok: true,
      canonicalId: legacyCanonical,
      source: "legacy_alias",
      input,
      legacyAlias: input,
    };
  }
  return { ok: false, code: "UNKNOWN_VEHICLE_TYPE", input };
}

function resolveVehicleTypeKeyFromLabel(label) {
  const resolution = resolveVehicleTypeKeyForRead(label);
  return resolution.ok ? resolution.canonicalId : "";
}

function assertCanonicalVehicleTypeKeyForWrite(raw) {
  const input = normalizeVehicleTypeInput(raw);
  if (!input) {
    const err = new Error("EMPTY_VEHICLE_TYPE");
    err.code = "EMPTY_VEHICLE_TYPE";
    throw err;
  }
  if (!CANONICAL_SET.has(input)) {
    const err = new Error(`NON_CANONICAL_VEHICLE_TYPE:${input}`);
    err.code = "NON_CANONICAL_VEHICLE_TYPE";
    err.input = input;
    throw err;
  }
  return input;
}

function getDefaultVehicleRate(canonicalId) {
  if (!isCanonicalVehicleTypeKey(canonicalId)) {
    const err = new Error(`UNKNOWN_VEHICLE_TYPE:${canonicalId}`);
    err.code = "UNKNOWN_VEHICLE_TYPE";
    throw err;
  }
  return DEFAULT_VEHICLE_RATES[canonicalId];
}

function lookupPricingVehicleEntry(vehiclesMap, resolution) {
  const vehicles = vehiclesMap && typeof vehiclesMap === "object" ? vehiclesMap : {};
  const { canonicalId, input, legacyAlias } = resolution;
  if (vehicles[canonicalId]) return vehicles[canonicalId];
  if (input && vehicles[input]) return vehicles[input];
  if (legacyAlias && legacyAlias !== canonicalId && vehicles[legacyAlias]) {
    return vehicles[legacyAlias];
  }
  return null;
}

function resolveKnownVehicleRateFromMap(vehiclesMap, rawKey) {
  const resolution = resolveVehicleTypeKeyForRead(rawKey);
  if (!resolution.ok) {
    const err = new Error(`${resolution.code}:${resolution.input}`);
    err.code = resolution.code;
    err.diagnostic = resolution;
    throw err;
  }
  const entry = lookupPricingVehicleEntry(vehiclesMap, resolution);
  return {
    resolution,
    entry,
    defaults: getDefaultVehicleRate(resolution.canonicalId),
  };
}

function exportCatalogDataForParity() {
  return {
    schemaVersion: catalog.schemaVersion,
    catalogVersion: catalog.catalogVersion,
    canonicalVehicleIds: [...catalog.canonicalVehicleIds],
    legacyAliases: { ...catalog.legacyAliases },
    defaultRates: JSON.parse(JSON.stringify(catalog.defaultRates)),
    displayLabelKeys: { ...catalog.displayLabelKeys },
    nameAliases: JSON.parse(JSON.stringify(catalog.nameAliases || {})),
    validCommissionRange: { ...catalog.validCommissionRange },
  };
}

module.exports = {
  CATALOG_SCHEMA_VERSION: catalog.schemaVersion,
  CATALOG_VERSION: catalog.catalogVersion,
  CANONICAL_VEHICLE_IDS,
  LEGACY_VEHICLE_ALIASES,
  VEHICLE_DISPLAY_LABEL_KEYS,
  VALID_COMMISSION_RANGE,
  DEFAULT_VEHICLE_RATES,
  DEFAULT_PRICING,
  normalizeVehicleTypeInput,
  isCanonicalVehicleTypeKey,
  resolveVehicleTypeKeyForRead,
  resolveVehicleTypeKeyFromLabel,
  assertCanonicalVehicleTypeKeyForWrite,
  getDefaultVehicleRate,
  lookupPricingVehicleEntry,
  resolveKnownVehicleRateFromMap,
  exportCatalogDataForParity,
  __SOURCE_SHA256__: "778d1b6bfcf92295ff7303eec17f62d6921ae51790589756261330d4c9531273",
};
